#!/usr/bin/env php
<?php

/**
 * Set environment
 */
define('MAD_ENV', isset($_SERVER['MAD_ENV']) ? $_SERVER['MAD_ENV'] : 'development');
require_once dirname(dirname(__FILE__)).'/config/environment.php';


try {
    $script  = array_shift($argv);
    $version = array_shift($argv);
    $ver = preg_match('/VERSION=(\d*)/', $version, $match) ? $match[1] : null;
    Mad_Model_Migration_Migrator::migrate("/db/migrate/", $ver);

} catch (Exception $e) {
    echo $e->getMessage();
}
